version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE_URL=file:./db.sqlite
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.gptdash.rule=Host(`gptdash.datenspuren.de`)"
      # - "traefik.http.routers.gptdash.rule=Host(`gptdash.${WEBDOMAIN}`)"
      - "traefik.http.routers.gptdash.entrypoints=websecure"
      - "traefik.http.services.test.loadBalancer.server.port=3000"

networks:
  proxy:
    external: true
